services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d meu_banco"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://usuario:senha@db:5432/meu_banco
    ports:
      - "8000:8000"
      - "8001:8001"  
    volumes:
      - .:/app
      - ./meu_projeto/static:/app/meu_projeto/static  
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 4 meu_projeto.wsgi:application"

volumes:
  postgres_data: